# Based on http://conda.pydata.org/docs/travis.html
language: python
sudo: false # use container based build
notifications:
  email: false

matrix:
  fast_finish: true

python:
  - 2.7
  - 3.4
  - 3.5

env:
  - CONDA_PACKAGES="numpy scipy pytest future"

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.16.0-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.16.0-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:
  #- conda install anaconda=2.4
  #- conda create --name testoceanmodes --file oceanmodes-exported-packages.txt
  #- source activate testoceanmodes
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION $CONDA_PACKAGES --file oceanmodes_exported_packages.txt
  - source activate test-environment
  - pip install codecov pytest-cov
  - pip install -e .

script:
  - py.test oceanmodes --cov=oceanmodes --cov-config .coveragerc --cov-report term-missing -v

after_success:
  - codecov
